// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwvayKBW7O0uPOfIeSD6iZH4CNFBuNrak',
    appId: '1:996152347930:web:231d6174500d2eb75030a3',
    messagingSenderId: '996152347930',
    projectId: 'notes-app-64b75',
    authDomain: 'notes-app-64b75.firebaseapp.com',
    storageBucket: 'notes-app-64b75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvcXXxjiDGyuLsK1e_kDTTPr8QKVvxgtc',
    appId: '1:996152347930:android:89e36f7fea68fbd15030a3',
    messagingSenderId: '996152347930',
    projectId: 'notes-app-64b75',
    storageBucket: 'notes-app-64b75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30TLGUUBOAecjmKk15zbXqkPNXOWZQck',
    appId: '1:996152347930:ios:0af2e7a364729aa35030a3',
    messagingSenderId: '996152347930',
    projectId: 'notes-app-64b75',
    storageBucket: 'notes-app-64b75.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );
}
